#!/usr/bin/python
# MD-Tracks is a statistical analysis toolkit for molecular dynamics
# and monte carlo simulations.
# Copyright (C) 2007 - 2010 Toon Verstraelen <Toon.Verstraelen@UGent.be>, Center
# for Molecular Modeling (CMM), Ghent University, Ghent, Belgium; all rights
# reserved unless otherwise stated.
#
# This file is part of MD-Tracks.
#
# MD-Tracks is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 3
# of the License, or (at your option) any later version.
#
# In addition to the regulations of the GNU General Public License,
# publications and communications based in parts on this program or on
# parts of this program are required to cite the following article:
#
# "MD-TRACKS: A productive solution for the advanced analysis of Molecular
# Dynamics and Monte Carlo simulations", Toon Verstraelen, Marc Van Houteghem,
# Veronique Van Speybroeck and Michel Waroquier, Journal of Chemical Information
# and Modeling, 48 (12), 2414-2424, 2008
# DOI:10.1021/ci800233y
#
# MD-Tracks is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <http://www.gnu.org/licenses/>
#
# --


from tracks.core import load_track, dump_track
from tracks.parse import parse_x_step
from tracks.optparse import add_quiet_option, add_cor_time_unit, \
    add_zero_mean_option
from tracks.log import log, usage_tail
from tracks.api import fit_cor_time

from molmod.units import parse_unit

import numpy
from optparse import OptionParser


usage = """%prog [options] input1 [input2 ...] {time_axis|time_step} output

%prog computes the average auto-correlation function for a set of tracks
(${input1}, ${input2}, ...) and stores the result in a track ${output}.
The normalized auto- correlation function will be stored in
${output}.normalized. The next-to-last argument is a track that contains the
time-axis, or it can also be the time step between two discrete data points.

This implementation does not use fast Fourier transforms. If you prefer
autocorrelation functions computed with the FFT method, see tr-ac-fft.

A simple exponential model is fitted to the normalized autocorrelation function
to estimated the correlation time. The fitted parameter is printed on screen.
""" + usage_tail

parser = OptionParser(usage)
parser.add_option(
    "-m", "--max-delta-t",
    help="Determines the maximum time-difference for which the auto- "
         "correlation has to be computed. This value defaults to half the "
         "track size. The lower this value, the better the statistical "
         "accuracy of the end result."
)
add_zero_mean_option(parser)
add_quiet_option(parser)
add_cor_time_unit(parser)
(options, args) = parser.parse_args()


log.verbose = options.verbose
if len(args) >= 3:
    paths_in = args[:-2]
    time_step = parse_x_step(args[-2])
    path_out = args[-1]
else:
    parser.error("Expecting at least three arguments.")

time_unit = parse_unit(options.time_unit)

length = len(load_track(paths_in[0]))
if options.max_delta_t is None:
    max_delta_steps = length/2
else:
    max_delta_steps = int(parse_unit(options.max_delta_t)/time_step)
    if max_delta_steps <= 0:
        parser.error("The option --max-delta-t must be strictly positive.")
average_steps = length - max_delta_steps
average_time = average_steps*time_step

result = 0
for path_in in paths_in:
    f = load_track(path_in)
    if len(f) != length:
        raise ValueError("All input tracks must have the same length.")
    if not options.zero_mean:
        f = f - f.mean()
    tmp = numpy.correlate(f, f[:average_steps], 'valid')/average_steps
    result += tmp
    log("PROCESSED %s" % path_in)
result /= len(paths_in)

dump_track(path_out, result)
log("WRITTEN %s" % path_out)
result /= result[0]
dump_track("%s.normalized" % path_out, result)
log("WRITTEN %s.normalized" % path_out)

cor_time = fit_cor_time(time_step, result)
log("Correlation time [%s]: %.3f" % (options.time_unit, cor_time/time_unit))


