#!/usr/bin/python
# Tracks provides tools for analyzing large trajectory files.
# Copyright (C) 2007 Toon Verstraelen <Toon.Verstraelen@UGent.be>
#
# This file is part of Tracks.
#
# Tracks is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 3
# of the License, or (at your option) any later version.
#
# Tracks is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <http://www.gnu.org/licenses/>
#
# --


from tracks.core import load_track, dump_track
from tracks.parse import parse_x_step, parse_slice
from tracks.optparse import add_quiet_option, add_slice_option
from tracks.log import log
from molmod.units import parse_unit

import numpy
from optparse import OptionParser


usage = """%prog [options] input {time_axis|timestep}

%prog applies the block average method track ${input}. It prints out a line with
estimates of the following values:
 * the mean
 * the error on the mean
 * the correlation time
 * the statistical inefficiency

%prog -h prints out all available options."""

parser = OptionParser(usage)
parser.add_option(
    "--plot-error",
    help="Plot the relation between blocksize and statistical error on "
         "the mean, and save the figure as ${PLOT_ERROR}.",
)
parser.add_option(
    "--plot-ctime",
    help="Plot the relation between blocksize and the correlation time, and "
         "save the figure as ${PLOT_CTIME}.",
)
parser.add_option(
    "-u", "--unit", default='au',
    help="The mean and error are printed in the given UNIT. [default=%default]",
)
parser.add_option(
    "-t", "--time-unit", default='au',
    help="The correlation time is printed in the given TIME_UNIT. [default=%default]",
)
add_quiet_option(parser)
parser.add_option(
    "-b", "--min-blocks", default="100",
    help="The minimum number of blocks to be considered."
)
add_slice_option(parser)
(options, args) = parser.parse_args()


class Error(Exception):
    pass


log.verbose = options.verbose
if len(args) == 2:
    path_in = args[0]
    time_step = parse_x_step(args[1])
else:
    parser.error("Expecting two arguments.")

min_blocks = int(options.min_blocks)
sub = parse_slice(options.slice)
f = load_track(path_in, sub)

x = [] # block sizes
y = [] # error on the mean
c = [] # correlation time
s = [] # statistical inefficiency

for block_size in xrange(1, len(f)/min_blocks):
    n_blocks = len(f)/block_size
    total_size = n_blocks * block_size
    averages = numpy.array([
        f[i*block_size:(i+1)*block_size].mean() for i in xrange(n_blocks)
    ], float)

    x.append(block_size*time_step)
    y.append(averages.std()/numpy.sqrt(n_blocks))
    c.append(0.5*averages.var()/f[:total_size].var()*block_size*time_step)
    s.append(averages.var()/f[:total_size].var()*block_size)

x = numpy.array(x)
y = numpy.array(y)
c = numpy.array(c)
s = numpy.array(s)

l = len(y)*2/3
if l == 0:
    raise Error("Too few blocks to do a proper estimate of the error.")
unit = parse_unit(options.unit)
time_unit = parse_unit(options.time_unit)

select = numpy.arange(len(x)-l, len(x))
# perform a fit with a + b/t, a is an estimate of the error
(yinf, by), resids, rank, svals = numpy.linalg.lstsq(
    numpy.array([numpy.ones(len(select), float), 1/x[select]]).transpose(),
    y[select],
)

select = select[numpy.isfinite(c[select])]
if len(select) > 3:
    (cinf, bc), resids, rank, svals = numpy.linalg.lstsq(
        numpy.array([numpy.ones(len(select), float), 1/x[select]]).transpose(),
        c[select],
    )
    (sinf, bs), resids, rank, svals = numpy.linalg.lstsq(
        numpy.array([numpy.ones(len(select), float), 1/x[select]]).transpose(),
        s[select],
    )
else:
    cinf = numpy.inf
    sinf = numpy.inf


print "%s %s %s %s" % (f.mean()/unit, yinf/unit, cinf/time_unit, sinf)

if options.plot_error is not None:
    import pylab
    pylab.clf()
    pylab.title("Block average plot for %s" % path_in)
    pylab.xlabel("Block size [%s]" % options.time_unit)
    pylab.ylabel("Error on the mean [%s]" % options.unit)
    pylab.plot(x/time_unit,y/unit,"k+")
    pylab.plot(x[-l:]/time_unit,(yinf+by/x[-l:])/unit,"r-", linewidth=1)
    pylab.axhline(yinf/unit, color="r", linewidth=1)
    pylab.grid(True,linestyle="-",linewidth=0.2, alpha=0.5)
    pylab.savefig(options.plot_error)

if options.plot_ctime is not None:
    import pylab
    pylab.clf()
    pylab.title("Block average plot for %s" % path_in)
    pylab.xlabel("Block size [%s]" % options.time_unit)
    pylab.ylabel("Correlation time [%s]" % options.time_unit)
    pylab.plot(x/time_unit,c/time_unit,"k+")
    pylab.plot(x[-l:]/time_unit,(cinf+bc/x[-l:])/time_unit,"r-", linewidth=1)
    pylab.axhline(cinf/time_unit, color="r", linewidth=1)
    pylab.grid(True,linestyle="-",linewidth=0.2, alpha=0.5)
    pylab.savefig(options.plot_ctime)


