#!/usr/bin/python
# Tracks provides tools for analyzing large trajectory files.
# Copyright (C) 2007 Toon Verstraelen <Toon.Verstraelen@UGent.be>
#
# This file is part of Tracks.
#
# Tracks is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 3
# of the License, or (at your option) any later version.
#
# Tracks is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <http://www.gnu.org/licenses/>
#
# --


from tracks.core import dump_track
from tracks.parse import parse_slice
from tracks.log import log
import tracks.vector as vector

import numpy
from optparse import OptionParser


usage = """%prog [options] pos_prefix1 pos_prefix2 pos_prefix3 [vel_prefix1 vel_prefix2 vel_prefix3] pos_output [vel_output]

%prog computes the bending angle, defined by pos_prefix1-pos_prefix2-pos_prefix3,
for all time steps. Tracks with the given prefixes must exist, and their
filenames must look like: ${pos_prefix*}.c, where c is x, y or z. The output is
stored in ${pos_output}.

If the arguments ${vel_prefix*} are given, also the time derivative of the
bending angle is computed. Tracks with the given prefixes must exist, and their
filenames must look like: ${vel_prefix*}.c, where c is x, y or z. The output is
stored in ${vel_output}.

%prog -h prints out all available options."""

parser = OptionParser(usage)
parser.add_option(
    "-s", "--slice", default="::",
    help="Subsample the input tracks with the given slice start:stop:step "
         "where start, stop and step must be integers or can be omitted. "
         "The slice interpretation is pythonic. [default=%default]",
)
parser.add_option(
    "-c", "--cos", action="store_true", default=False,
    help="Compute the cosine instead of the angle."
)
parser.add_option(
    "-q", "--quiet", action="store_false", dest="verbose", default=True,
    help="Don't print any output."
)
(options, args) = parser.parse_args()


log.verbose = options.verbose
if len(args) == 4:
    pos_prefix1, pos_prefix2, pos_prefix3, pos_output_path = args
    vel_prefix1 = None
    vel_prefix2 = None
    vel_prefix3 = None
    vel_output_path = None
elif len(args) == 8:
    pos_prefix1, pos_prefix2, pos_prefix3, vel_prefix1, vel_prefix2, vel_prefix3, pos_output_path, vel_output_path = args
else:
    parser.error("Expecting four or eight arguments.")

sub = parse_slice(options.slice)
if vel_prefix1 is None:
    dump_track(pos_output_path, vector.bend(
        vector.TrackVector.from_prefix(pos_prefix1, sub),
        vector.TrackVector.from_prefix(pos_prefix2, sub),
        vector.TrackVector.from_prefix(pos_prefix3, sub),
        return_cos=options.cos,
    ))
    log("WRITTEN: %s" % pos_output_path)
else:
    pos_bend, vel_bend = vector.bend(
        vector.TrackVector.from_prefix(pos_prefix1, sub),
        vector.TrackVector.from_prefix(pos_prefix2, sub),
        vector.TrackVector.from_prefix(pos_prefix3, sub),
        vector.TrackVector.from_prefix(vel_prefix1, sub),
        vector.TrackVector.from_prefix(vel_prefix2, sub),
        vector.TrackVector.from_prefix(vel_prefix3, sub),
        return_cos=options.cos,
    )
    dump_track(pos_output_path, pos_bend)
    log("WRITTEN: %s" % pos_output_path)
    dump_track(vel_output_path, vel_bend)
    log("WRITTEN: %s" % vel_output_path)



