#!/usr/bin/python
# Tracks provides tools for analyzing large trajectory files.
# Copyright (C) 2007 Toon Verstraelen <Toon.Verstraelen@UGent.be>
#
# This file is part of Tracks.
#
# Tracks is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 3
# of the License, or (at your option) any later version.
#
# Tracks is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <http://www.gnu.org/licenses/>
#
# --

from tracks import dihed_track, dump_track, parse_slice
import numpy, glob, os
from optparse import OptionParser

usage = """Usage: %prog [options] prefix1 prefix2 prefix3 prefix4 output
%prog computes the dihedral angled prefix1-prefix2-prefix3-prefix4 for all time
steps. Tracks with the given prefixes must exist, and their filenames must look
like: ${prefix1}.c, ${prefix2}.c, ${prefix3}.c and ${prefix4}.c where c is x, y
or z. The output is stored in ${output}.

%prog -h prints out all available options."""

parser = OptionParser(usage)
parser.add_option(
    "-s", "--slice", 
    help="sample the input tracks with the given slice start:stop:step "
         "where start, stop and step must be integers or can be omitted. "
         "The slice interpretation is pythonic. [default=%default]",
    default="::"
)
(options, args) = parser.parse_args()

if len(args) == 5:
    prefix1, prefix2, prefix3, prefix4, output_path = args
else:
    parser.error("Expecting five arguments.")

sub = parse_slice(options.slice)
dump_track(output_path, dihed_track(prefix1, prefix2, prefix3, prefix4, sub))
    


