#!/usr/bin/python
# Tracks provides tools for analyzing large trajectory files.
# Copyright (C) 2007 Toon Verstraelen <Toon.Verstraelen@UGent.be>
#
# This file is part of Tracks.
#
# Tracks is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 3
# of the License, or (at your option) any later version.
#
# Tracks is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <http://www.gnu.org/licenses/>
#
# --


from tracks import load_track, dump_track, parse_slice
import numpy
from optparse import OptionParser


usage = """Usage: %prog [options] input slice output
%prog slices the input track and writes the result to the output track.

The slice argument has the following format:
start:stop:step
where start, stop and step must be integers or can be omitted.
The slice interpretation is pythonic.

%prog -h prints out all available options."""

parser = OptionParser(usage)
(options, args) = parser.parse_args()


if len(args) == 3:
    path_in, sub, path_out = args
else:
    parser.error("Expecting three arguments.")

sub = parse_slice(sub)
dump_track(path_out, load_track(path_in)[sub])
