#!/usr/bin/python
# MD-Tracks is a statistical analysis toolkit for molecular dynamics
# and monte carlo simulations.
# Copyright (C) 2007 - 2009 Toon Verstraelen <Toon.Verstraelen@UGent.be>, Center
# for Molecular Modeling (CMM), Ghent University, Ghent, Belgium; all rights
# reserved unless otherwise stated.
#
# This file is part of MD-Tracks.
#
# MD-Tracks is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 3
# of the License, or (at your option) any later version.
#
# In addition to the regulations of the GNU General Public License,
# publications and communications based in parts on this program or on
# parts of this program are required to cite the following article:
#
# "MD-TRACKS: A productive solution for the advanced analysis of Molecular
# Dynamics and Monte Carlo simulations", Toon Verstraelen, Marc Van Houteghem,
# Veronique Van Speybroeck and Michel Waroquier, Journal of Chemical Information
# and Modeling, 48 (12), 2414-2424, 2008
# DOI:10.1021/ci800233y
#
# MD-Tracks is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <http://www.gnu.org/licenses/>
#
# --


from tracks.core import dump_track
from tracks.api.cell import TrackCell
from tracks.api.vector import TrackVector
from tracks.optparse import add_quiet_option, add_cell_option
from tracks.log import usage_tail

from optparse import OptionParser


usage = """%prog [options] prefix_a1 [prefix_a2 ...] - prefix_b1 [prefix_b2] output

%prog computes the shortest distance at each time step between the Cartesian
coordinates in the files ${prefix_a*}.${c} and ${prefix_b*}.${c}, where ${c}
is x, y or z. The result is written to ${output}.
""" + usage_tail

parser = OptionParser(usage)
add_quiet_option(parser)
add_cell_option(parser)
(options, args) = parser.parse_args()

if len(args) < 3:
    parser.error("Expecting at least three arguments.")
path_out = args[-1]
prefixes_a, prefixes_b = " ".join(args[:-1]).split(" - ")
prefixes_a = prefixes_a.split()
if len(prefixes_a) == 0:
    parser.error("At least one prefix_a expected.")
prefixes_b = prefixes_b.split()
if len(prefixes_b) == 0:
    parser.error("At least one prefix_b expected.")

if options.unit_cell_str is None:
    cell = None
else:
    cell = TrackCell.from_cell_str(options.unit_cell_str)

shortest_distances = None

for prefix_a in prefixes_a:
    vec_a = TrackVector.from_prefix(prefix_a)
    for prefix_b in prefixes_b:
        vec_b = TrackVector.from_prefix(prefix_b)
        delta = vec_a - vec_b
        if cell is not None:
            delta = cell.shortest_vector(delta)
        distances = delta.norm()
        if shortest_distances is None:
            shortest_distances = distances
        else:
            selection = distances < shortest_distances
            shortest_distances[selection] = distances[selection]

dump_track(path_out, shortest_distances)


